name: Update dependencies with Renovate

on:
  schedule:
    - cron: "0 0 * * 1" # every Monday 00:00 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout commit
        uses: actions/checkout@v5
      - name: Run Renovate
        uses: renovatebot/github-action@v44.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate-config.json
        env:
          LOG_LEVEL: "debug"
          RENOVATE_REPOSITORIES: ${{ github.repository }}
